language: node_js
node_js:
  - "10"
dist: trusty
sudo: false
services:
  - docker

cache:
  directories:
    - node_modules

install:
  - npm install

script:
  - npm run test
  - npm run build
  - npm run build:docker
deploy:
  skip_cleanup: true
  provider: script
  script:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - docker push felixbreuer/instapy-webserver:latest
    - docker push felixbreuer/instapy-services:latest
  on:
    branch: master
