language: node_js
node_js:
  - 10
dist: trusty
sudo: false
services:
  - docker

cache:
  directories:
    - node_modules

install:
  - npm install

script:
  - npm run test
  - npm run build
  - docker-compose -f docker-compose.travis.yml build
deploy:
  skip_cleanup: true
  provider: script
  script: bash scripts/deploy_docker.sh
  on:
    branch: master
