version: '3'
services:
  auth:
    image: felixbreuer/instapy-auth:latest
    restart: unless-stopped
    environment:
      - MONGO_URL
      - JWT_SECRET
    networks:
      - instapy-net
  config:
    image: felixbreuer/instapy-config:latest
    restart: unless-stopped
    environment:
      - MONGO_URL
      - JWT_SECRET
      - CIPHER_SECRET
    networks:
      - instapy-net
  socket:
    image: felixbreuer/instapy-socket:latest
    restart: unless-stopped
    environment:
      - JWT_SECRET
    networks:
      - instapy-net
  webserver:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ./conf/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - instapy-net

networks:
  instapy-net:
    driver: bridge