version: '3'
services:
  config:
    build: ./services/config
    image: felixbreuer/instapy-config:latest
  auth:
    build: ./services/auth
    image: felixbreuer/instapy-auth:latest
  socket:
    build: ./services/socket
    image: felixbreuer/instapy-socket:latest