version: '3'
services:
  auth:
    image: felixbreuer/instapy-auth:latest
    restart: unless-stopped
    environment:
      - MONGO_URL
      - JWT_SECRET
      - VIRTUAL_HOST=auth.instapy.io
      - LETSENCRYPT_HOST=auth.instapy.io
  config:
    image: felixbreuer/instapy-config:latest
    restart: unless-stopped
    environment:
      - MONGO_URL
      - JWT_SECRET
      - CIPHER_SECRET
      - VIRTUAL_HOST=api.instapy.io
      - LETSENCRYPT_HOST=api.instapy.io
  socket:
    image: felixbreuer/instapy-socket:latest
    restart: unless-stopped
    environment:
      - JWT_SECRET
      - VIRTUAL_HOST=socket.instapy.io
      - LETSENCRYPT_HOST=socket.instapy.io
