version: '3'
services:
  instapy:
    volumes:
      - ./services/instapy:/usr/instapy
  config:
    volumes:
      - ./services/config:/usr/instapy
    environment:
      - MODE=development
    ports:
      - 3002:80
  socket:
    command: ['npm', 'run', 'dev']
    volumes:
      - ./services/socket:/usr/instapy
    ports:
      - 3001:80
  grafana:
    volumes:
      - ./conf/grafana/grafana.ini:/etc/grafana/grafana.ini
      - ./conf/grafana/datasources:/etc/grafana/provisioning/datasources
      - ./conf/grafana/dashboards:/etc/grafana/provisioning/dashboards
