version: '3'
services:
  auth:
    image: felixbreuer/instapy-auth:latest
    restart: unless-stopped
    environment:
      - MONGO_URL
      - JWT_SECRET
      - VIRTUAL_HOST=auth.instapy.io
      - VIRTUAL_PORT=443
      - VIRTUAL_PROTO=https
      - LETSENCRYPT_HOST=auth.instapy.io
    networks:
      - instapy-net
  config:
    image: felixbreuer/instapy-config:latest
    restart: unless-stopped
    environment:
      - MONGO_URL
      - JWT_SECRET
      - CIPHER_SECRET
      - VIRTUAL_HOST=api.instapy.io
      - VIRTUAL_PORT=443
      - VIRTUAL_PROTO=https
      - LETSENCRYPT_HOST=api.instapy.io
    networks:
      - instapy-net
  socket:
    image: felixbreuer/instapy-socket:latest
    restart: unless-stopped
    environment:
      - JWT_SECRET
      - VIRTUAL_HOST=socket.instapy.io
      - VIRTUAL_PORT=443
      - VIRTUAL_PROTO=https
      - LETSENCRYPT_HOST=socket.instapy.io
    networks:
      - instapy-net
  webserver:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ./conf/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - instapy-net
  nginx-proxy:
    image: jwilder/nginx-proxy:alpine
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - dhparam:/etc/nginx/dhparam
      - vhost:/etc/nginx/vhost.d
      - conf:/etc/nginx/conf.f
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - certs:/etc/nginx/certs
    labels:
      - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy"
  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    environment:
      - DEFAULT_EMAIL=hi@felixbreuer.me
    volumes:
      - vhost:/etc/nginx/vhost.d
      - conf:/etc/nginx/conf.f
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - certs:/etc/nginx/certs
    depends_on:
      - nginx-proxy

networks:
  instapy-net:
    driver: bridge

volumes:
  certs:
  dhparam:
  vhost:
  conf:
  html:
