version: '3'
services:
  instapy:
    build: ./services/instapy
    image: felixbreuer/instapy:latest
    volumes:
      - instapy-data:/usr/instapy/InstaPy
    environment:
      - INFLUXDB_DB=instapy
      - INFLUXDB_USER=instapy
      - INFLUXDB_PASSWORD=instapysecret
      - INFLUXDB_HOST=influxdb
    networks:
      - instapy-net
  webserver:
    build:
      context: .
      dockerfile: conf/webserver.Dockerfile
    image: felixbreuer/instapy-webserver:latest
    restart: unless-stopped
    depends_on:
      - config
      - auth
      - socket
      - influxdb
      - grafana
    ports:
      - 80:80
    networks:
      - instapy-net
  config:
    build: ./services/config
    image: felixbreuer/instapy-config:latest
    restart: unless-stopped
    ports:
      - 4002:80
    environment:
      - MONGO_URL
      - JWT_SECRET
      - CIPHER_SECRET
    networks:
      - instapy-net
  auth:
    build: ./services/auth
    image: felixbreuer/instapy-auth:latest
    restart: unless-stopped
    ports:
      - 4001:80
    environment:
      - MONGO_URL
      - JWT_SECRET
    networks:
      - instapy-net
  socket:
    build: ./services/socket
    image: felixbreuer/instapy-socket:latest
    restart: unless-stopped
    depends_on:
      - instapy
    environment:
      - FILESYSTEM=unix
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - instapy-net
  influxdb:
    image: influxdb:alpine
    restart: unless-stopped
    volumes:
      - instapy-influxdb:/var/lib/influxdb
    environment:
      - INFLUXDB_DB=instapy
      - INFLUXDB_ADMIN_USER=instapy
      - INFLUXDB_ADMIN_PASSWORD=instapysecret
    networks:
      - instapy-net
  grafana:
    build:
      context: .
      dockerfile: conf/grafana.Dockerfile
    image: felixbreuer/instapy-grafana:latest
    restart: unless-stopped
    depends_on:
      - influxdb
    volumes:
      - instapy-grafana:/var/lib/grafana
    ports:
      - 3000:3000
    environment:
      - INFLUXDB_URL=http://influxdb:8086
      - INFLUXDB_USERNAME=instapy
      - INFLUXDB_PASSWORD=instapysecret
      - INFLUXDB_DB=instapy
      - GF_SECURITY_ADMIN_USER=instapy
      - GF_SECURITY_ADMIN_PASSWORD=instapysecret
    networks:
      - instapy-net

networks:
  instapy-net:
    driver: bridge

volumes:
  instapy-data:
  instapy-influxdb:
  instapy-grafana:
