version: '3'
services:
  auth:
    image: felixbreuer/instapy-auth:latest
    restart: unless-stopped
    ports:
      - 4001:80
    environment:
      - MONGO_URL
      - JWT_SECRET
  config:
    image: felixbreuer/instapy-config:latest
    container_name: instapy-config
    restart: unless-stopped
    ports:
      - 4002:80
    environment:
      - MONGO_URL
      - JWT_SECRET
      - CIPHER_SECRET